const foods = [
  { id: 1, name: "Pancakes", category: "Breakfast", price: 120, image: "/images/food1.jpg" },
  { id: 2, name: "Omelette", category: "Breakfast", price: 100, image: "/images/food2.jpg" },
  { id: 3, name: "French Toast", category: "Breakfast", price: 130, image: "/images/food3.jpg" },
  { id: 4, name: "Cereal Bowl", category: "Breakfast", price: 90, image: "/images/food4.jpg" },
  { id: 5, name: "Smoothie", category: "Drinks", price: 150, image: "/images/food5.jpg" },
  { id: 6, name: "Bagel Sandwich", category: "Breakfast", price: 110, image: "/images/food6.jpg" },
  { id: 7, name: "Veg Burger", category: "Main course", price: 180, image: "/images/food7.jpg" },
  { id: 8, name: "Chicken Burger", category: "Main course", price: 200, image: "/images/food8.jpg" },
  { id: 9, name: "Pizza Margherita", category: "Main course", price: 250, image: "/images/food9.jpg" },
  { id: 10, name: "Pasta Alfredo", category: "Main course", price: 220, image: "/images/food10.jpg" },
  { id: 11, name: "Grilled Sandwich", category: "Main course", price: 170, image: "/images/food11.jpg" },
  { id: 12, name: "Fried Rice", category: "Main course", price: 200, image: "/images/food12.jpg" },
  { id: 13, name: "Veg Curry", category: "Main course", price: 190, image: "/images/food13.jpg" },
  { id: 14, name: "Chicken Curry", category: "Main course", price: 220, image: "/images/food14.jpg" },
  { id: 15, name: "Chocolate Cake", category: "Dessert", price: 180, image: "/images/food15.jpg" },
  { id: 16, name: "Brownie", category: "Dessert", price: 150, image: "/images/food16.jpg" },
  { id: 17, name: "Ice Cream", category: "Dessert", price: 120, image: "/images/food17.jpg" },
  { id: 18, name: "Fruit Tart", category: "Dessert", price: 160, image: "/images/food18.jpg" },
  { id: 19, name: "Cupcake", category: "Dessert", price: 100, image: "/images/food19.jpg" },
  { id: 20, name: "Chocolate Pudding", category: "Dessert", price: 140, image: "/images/food20.jpg" },
  { id: 21, name: "Tomato Soup", category: "Soup", price: 120, image: "/images/food21.jpg" },
  { id: 22, name: "Chicken Soup", category: "Soup", price: 140, image: "/images/food22.jpg" },
  { id: 23, name: "Veg Minestrone", category: "Soup", price: 130, image: "/images/food23.jpg" },
  { id: 24, name: "Cream of Mushroom", category: "Soup", price: 150, image: "/images/food24.jpg" },
  { id: 25, name: "Carrot Soup", category: "Soup", price: 130, image: "/images/food25.jpg" },
  { id: 26, name: "Lemonade", category: "Drinks", price: 80, image: "/images/food26.jpg" },
  { id: 27, name: "Cold Coffee", category: "Drinks", price: 120, image: "/images/food27.jpg" },
  { id: 28, name: "Orange Juice", category: "Drinks", price: 90, image: "/images/food28.jpg" },
  { id: 29, name: "Milkshake", category: "Drinks", price: 130, image: "/images/food29.jpg" },
  { id: 30, name: "Iced Tea", category: "Drinks", price: 100, image: "/images/food30.jpg" },
  { id: 31, name: "Strawberry Smoothie", category: "Drinks", price: 120, image: "/images/food31.jpg" },
  { id: 32, name: "Caesar Salad", category: "Salads", price: 140, image: "/images/food32.jpg" },
  { id: 33, name: "Greek Salad", category: "Salads", price: 150, image: "/images/food33.jpg" },
  { id: 34, name: "Fruit Salad", category: "Salads", price: 120, image: "/images/food34.jpg" },
  { id: 35, name: "Garden Salad", category: "Salads", price: 130, image: "/images/food35.jpg" },
  { id: 36, name: "Quinoa Salad", category: "Salads", price: 160, image: "/images/food36.jpg" },
  { id: 37, name: "Cobb Salad", category: "Salads", price: 150, image: "/images/food37.jpg" },
  { id: 38, name: "Veg Sandwich", category: "Main course", price: 180, image: "/images/food38.jpg" },
  { id: 39, name: "Chicken Nuggets", category: "Main course", price: 200, image: "/images/food39.jpg" },
  { id: 40, name: "Pasta Bolognese", category: "Main course", price: 230, image: "/images/food40.jpg" }]

export default foods;
